spring.application.name=spring-backend
spring.datasource.url=jdbc:sqlite:../backend/app/database/finguard.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=optional:file:../.env[.properties]

finguard.fastapi.base-url=http://127.0.0.1:8000

logging.level.org.springframework.security=DEBUG